title: Ekiras
email: ekirastogi@gmail.com
description: Awesome blog tutorials
baseurl: ""
url: "https://ekirastogi.github.io"
twitter_username: ekirastogi
github_username:  ekirastogi

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

includes:
  - pages

################################
# Disqus Comments
################################
disqus:
  shortname: ekiras

################################
# Analytics Settings
################################
google_analytics: UA-56017203-1
google_analytics_async: true


permalink: /:categories/:title

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
