title: Ekiras
email: ekirastogi@gmail.com
author: Ekansh Rastogi
description: Awesome blog tutorials
baseurl: ""
url: "http://www.ekiras.com"
twitter_username: ekirastogi
github_username:  ekirastogi

################################
# Markdown Settings
################################
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

theme: minima

################################
# Plugins Settings
################################
plugins:
  - jekyll-feed
#  - jekyll-toc
#  - jekyll-redirect-from
#  - jekyll-seo-tag

#whitelist:
#  - jekyll-redirect-from

includes:
  - pages

################################
# Disqus Comments
################################
disqus:
  shortname: ekiras

################################
# Analytics Settings
################################
google_analytics: UA-56017203-1
google_analytics_async: true


permalink: /:categories:/title

collections:
  dumps:
    output: true
    permalink: /:year/:month/:title

# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/